version: '3' 
services:
  
  namenode:
    build: ./components/namenode
    container_name: namenode
    volumes:
      - ./volume-data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=bigdatagrapescluster
    env_file:
      - ./config/hadoop.env
    ports:
      - 50070:50070
      - 8020:8020
  
  datanode:
    build: ./components/datanode
    depends_on: 
      - namenode
    volumes:
      - ./volume-data/datanode:/hadoop/dfs/data
    env_file:
      - ./config/hadoop.env
    ports:
      - 50075:50075

  spark-geo-worker:
    build: ./components/spark-geo-worker
    depends_on:
      - spark-master
    env_file:
      - ./config/hadoop.env

  spark-master:
    build: ./components/spark-master
    container_name: spark-master
    depends_on: 
      - namenode
    volumes:
      - ./volume-data/raster-processing:/bashes
    ports:
      - 8080:8080
      - 7077:7077
      - 6066:6066
      - 8002:8002
      - 8001:8001
    env_file:
      - ./config/hadoop.env

  hue:
    build: ./components/hue
    container_name: hue
    ports:
      - 8088:8088
    environment:
      - NAMENODE_HOST=namenode
